### ISSUE TITLE
Cannot install module 

### ISSUE THREAD

**Issue by kevincherian** [eojthebrave/icecream#4]
I tried to install the module, but it doesn't work. 
When I go to the page, it says page not found. Please help.

**Comment by eojthebrave** [comment]
I just tried installing the latest version of this module, with the latest Drupal 8 HEAD. And it's working okay for me. I did have to clear the cache after updating HEAD. But, that seemed to fix it.

Could you try updating to the latest Drupal 8 HEAD, and clearing the cache just to be sure that it's not one of those things that's causing the problems.

If it's still now working after that, are you seeing any errors on the page? How about in your PHP error log?

**Comment by kevincherian** [comment]
Hey, I'm using drupal 8.0.0 beta 10 and it just doesn't install the module. It gives me the pluginnotfound exception

**Comment by kevincherian** [comment]
[Drupal\Component\Plugin\Exception\PluginNotFoundException]  
  The "entity:node" plugin does not exist.                     

This is the error I get.
